### ISSUE TITLE
Linter for PRs

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/tres#212]
Add a `lint-pr.yaml` to the CI/CD to check quality of PRs using https://github.com/amannn/action-semantic-pull-request

```
feat(ui): Add `Button` component
^    ^    ^
|    |    |__ Subject
|    |_______ Scope
|____________ Type
```

```
name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
